Update github action config

diff --git a/.github/workflows/docker-web-server.yml b/.github/workflows/docker-web-server.yml
--- a/.github/workflows/docker-web-server.yml
+++ b/.github/workflows/docker-web-server.yml
@@ -14,10 +14,15 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    - name: Echo TEST environment secret
+    - name: Check the existance of the environment secret TEST
+      env:
+        TEST: ${{ secrets.TEST }}
       run: |
-        echo ${{ secrets.TEST }}
-      
+        if [[ -z "$TEST" ]]; then
+          echo "Assertion failed: The environment secret TEST is not found"
+          exit 1
+        fi
+
     - name: Cache Unity Dependencies
       uses: actions/cache@v2
       with:
